export type MissionType =
    | "connect_x"
    | "connect_google"
    | "connect_discord"
    | "connect_telegram"
    | "connect_twitch"
    | "x_follow"
    | "x_like"
    | "x_retweet"
    | "x_comment"
    | "google_subscribe"
    | "google_comment"
    | "telegram_join"
    | "discord_join"
    | "twitch_follow"
    | "twitch_subscribe"
    | "mailchimp_subscribe"
    | "link_visit"
    | "quiz"
    | "redeemable_code";

export type MissionStatus = "draft" | "active" | "paused" | "archived";

export type MissionFrequency =
    | "once"
    | "hourly"
    | "daily"
    | "weekly"
    | "monthly";

export type RewardType = "currency" | "multiplier" | "external";

export interface CurrencyRewardConfig {
    amount: number;
}

export interface MultiplierRewardConfig {
    value: number;
    durationSeconds: number;
}

export interface ExternalRewardConfig {
    name: string;
    description?: string;
}

export interface MissionReward {
    id: string;
    missionId: string;
    type: RewardType;
    currencyId: string | null;
    config: CurrencyRewardConfig | MultiplierRewardConfig | ExternalRewardConfig | null;
    currency?: Currency | null;
}

export interface Mission {
    id: string;
    tenantId: string;
    name: string;
    description: string | null;
    type: MissionType;
    config: Record<string, unknown>;
    frequency: MissionFrequency;
    startsAt: string;
    endsAt: string;
    status: MissionStatus;
    rewards?: MissionReward[];
}

export type SubmissionStatus = "pending" | "approved" | "rejected";

export interface MissionSubmission {
    id: string;
    missionId: string;
    userId: string;
    userData: Record<string, unknown> | null;
    status: SubmissionStatus;
    createdAt: string;
}

export interface Currency {
    id: string;
    name: string;
    symbol: string | null;
    metadata: Record<string, unknown>;
}

export type Platform =
    | "x"
    | "telegram"
    | "google"
    | "discord"
    | "twitch";

export interface UserBalance {
    id: string;
    userId: string;
    currencyId: string;
    balance: number;
    currency: Currency;
}

export interface UserMultiplier {
    id: string;
    userId: string;
    value: number;
    currencyId: string | null;
    /** ISO timestamp when this multiplier expires, null if permanent */
    expiresAt: string | null;
}

export interface LoyalOpsConfig {
    /** Your tenant public key */
    tenantPublicKey: string;
    /** JWT token generated by your backend to identify the user */
    userToken: string;
    /** API base URL. Defaults to https://api.loyalops.com/v1 */
    baseUrl?: string;
}
